services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_KEY=${API_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - nextjs_static:/app/.next
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - go_data:/root/data
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  nextjs_static:
  go_data:

networks:
  app-network:
    driver: bridge